AllCops:
  
  Exclude:
    - 'lib/**/*'
    - 'bin/*'
    - 'spec/dummy/**/*'
    - 'db/schema.rb'
    - 'Rakefile'
    - 'bundle/**/*'

Metrics/LineLength:
    Max: 150

Style/AsciiComments:
    Enabled: false

Style/Documentation:
    Enabled: false

Style/ClassAndModuleChildren:
    Enabled: false